import os
import psycopg2
from dotenv import load_dotenv

def setup_proyectos():
    load_dotenv(dotenv_path='../.env')
    
    host = os.getenv("SUPABASE_URL", "").strip()
    port = os.getenv("SUPABASE_PORT", "6543").strip()
    user = os.getenv("SUPABASE_USER", "").strip()
    password = os.getenv("SUPABASE_PASSWORD", "").strip()
    dbname = os.getenv("SUPABASE_DATABASE", "postgres").strip()
    
    db_url = f"postgresql://{user}:{password}@{host}:{port}/{dbname}?sslmode=require"
    print(f"Connecting to {host}:{port}...")
    
    try:
        conn = psycopg2.connect(db_url)
        cursor = conn.cursor()
        
        print("Creating table proyectos...")
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS public.proyectos (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                titulo VARCHAR(255) NOT NULL,
                descripcion TEXT,
                imagen_url TEXT,
                repo_url TEXT,
                demo_url TEXT,
                tecnologias TEXT[],
                created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
            );
        """)
        
        # Opcional: Permitir lecturas anónimas para la web pública (Asumiendo que RLS está activo)
        cursor.execute("""
            ALTER TABLE public.proyectos ENABLE ROW LEVEL SECURITY;
            
            DO $$
            BEGIN
              IF NOT EXISTS (
                SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'proyectos' AND policyname = 'Proyectos visibles para todos'
              ) THEN
                CREATE POLICY "Proyectos visibles para todos" ON public.proyectos FOR SELECT USING (true);
              END IF;
            END
            $$;
        """)
        
        conn.commit()
        print("✅ Database updated successfully! Table 'proyectos' created.")
        
        # NOTIFY API Cache
        cursor.execute("NOTIFY pgrst, 'reload schema';")
        conn.commit()
        
        cursor.close()
        conn.close()
    except Exception as e:
        print(f"Error updating database: {e}")

if __name__ == "__main__":
    setup_proyectos()
